name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release
      - develop

env:
  DOTNET_VERSION: "8.0.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        
      - name: Restore
        run: dotnet restore ./SistemaDeGestaoParaONGsDeAnimais.sln

      - name: Build
        run dotnet build ./SistemaDeGestaoParaONGsDeAnimais.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test ./SistemaDeGestaoParaONGsDeAnimais.sln --configuration Release --no-restore --no-build